name: mobile_app_coding_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  authentication_buttons: ^0.0.5
  http: ^1.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
